const menuItems = [
    {
        category: "Main Course",
        items: [
            {
                id: 1,
                name: "Margherita Pizza",
                description: "Classic pizza with fresh mozzarella and basil.",
                price: 9.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 2,
                name: "Grilled Chicken Sandwich",
                description: "Juicy chicken breast with fresh veggies.",
                price: 11.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 3,
                name: "Spaghetti Carbonara",
                description: "Classic Italian pasta with creamy sauce and pancetta.",
                price: 13.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 4,
                name: "Vegetarian Lasagna",
                description: "Layers of pasta with vegetables, cheese, and marinara sauce.",
                price: 12.49,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 5,
                name: "BBQ Ribs",
                description: "Slow-cooked ribs smothered in BBQ sauce.",
                price: 16.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 6,
                name: "Tandoori Chicken",
                description: "Indian spiced chicken roasted in a tandoor oven.",
                price: 14.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 7,
                name: "Fish and Chips",
                description: "Crispy battered fish served with golden fries.",
                price: 13.49,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 8,
                name: "Veggie Stir-Fry",
                description: "Assorted vegetables tossed in a savory soy sauce.",
                price: 10.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 9,
                name: "Chicken Alfredo",
                description: "Fettuccine pasta with creamy Alfredo sauce and grilled chicken.",
                price: 14.49,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 10,
                name: "Beef Tacos",
                description: "Soft tacos filled with seasoned beef, lettuce, and cheese.",
                price: 9.99,
                image: "https://via.placeholder.com/150",
            },
        ],
    },
    {
        category: "Desserts",
        items: [
            {
                id: 11,
                name: "Chocolate Lava Cake",
                description: "Warm chocolate cake with a gooey center.",
                price: 6.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 12,
                name: "Cheesecake",
                description: "Rich and creamy cheesecake with a graham cracker crust.",
                price: 7.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 13,
                name: "Tiramisu",
                description: "Classic Italian dessert with layers of coffee-soaked ladyfingers.",
                price: 8.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 14,
                name: "Apple Pie",
                description: "Traditional apple pie with a flaky crust.",
                price: 5.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 15,
                name: "Banana Split",
                description: "Banana topped with ice cream, whipped cream, and cherries.",
                price: 6.49,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 16,
                name: "Brownie Sundae",
                description: "Warm brownie topped with vanilla ice cream and chocolate sauce.",
                price: 7.49,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 17,
                name: "Panna Cotta",
                description: "Silky smooth Italian dessert topped with berry compote.",
                price: 8.49,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 18,
                name: "Fruit Tart",
                description: "Crispy tart filled with custard and fresh fruits.",
                price: 7.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 19,
                name: "Ice Cream Trio",
                description: "Three scoops of assorted ice cream flavors.",
                price: 6.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 20,
                name: "Creme Brulee",
                description: "Rich custard topped with caramelized sugar.",
                price: 8.99,
                image: "https://via.placeholder.com/150",
            },
        ],
    },
    {
        category: "Appetizers",
        items: [
            {
                id: 21,
                name: "Garlic Bread",
                description: "Toasted bread topped with garlic and butter.",
                price: 4.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 22,
                name: "Bruschetta",
                description: "Grilled bread with tomatoes, basil, and olive oil.",
                price: 5.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 23,
                name: "Stuffed Mushrooms",
                description: "Mushrooms stuffed with cheese and herbs.",
                price: 6.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 24,
                name: "Chicken Wings",
                description: "Crispy wings tossed in your choice of sauce.",
                price: 8.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 25,
                name: "Spring Rolls",
                description: "Crispy rolls filled with veggies and served with dipping sauce.",
                price: 6.49,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 26,
                name: "Mozzarella Sticks",
                description: "Fried mozzarella cheese served with marinara sauce.",
                price: 7.49,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 27,
                name: "Nachos",
                description: "Tortilla chips topped with cheese, jalapenos, and salsa.",
                price: 8.49,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 28,
                name: "Potato Skins",
                description: "Baked potato halves topped with cheese and bacon.",
                price: 7.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 29,
                name: "Calamari",
                description: "Fried squid rings served with marinara sauce.",
                price: 9.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 30,
                name: "Caprese Salad",
                description: "Tomatoes, mozzarella, and basil drizzled with balsamic glaze.",
                price: 6.99,
                image: "https://via.placeholder.com/150",
            },
        ],
    },
    {
        category: "Beverages",
        items: [
            {
                id: 31,
                name: "Cappuccino",
                description: "Espresso with steamed milk and foam.",
                price: 4.49,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 32,
                name: "Iced Tea",
                description: "Chilled tea with lemon and mint.",
                price: 3.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 33,
                name: "Fresh Orange Juice",
                description: "Freshly squeezed orange juice.",
                price: 4.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 34,
                name: "Lemonade",
                description: "Refreshing lemonade with a hint of mint.",
                price: 3.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 35,
                name: "Mango Smoothie",
                description: "Creamy mango smoothie blended with yogurt.",
                price: 5.49,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 36,
                name: "Hot Chocolate",
                description: "Rich hot chocolate topped with whipped cream.",
                price: 4.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 37,
                name: "Latte",
                description: "Smooth espresso with steamed milk.",
                price: 4.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 38,
                name: "Berry Smoothie",
                description: "Mixed berry smoothie with a hint of honey.",
                price: 5.49,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 39,
                name: "Sparkling Water",
                description: "Carbonated water served chilled.",
                price: 2.99,
                image: "https://via.placeholder.com/150",
            },
            {
                id: 40,
                name: "Espresso",
                description: "Strong and bold shot of espresso.",
                price: 3.49,
                image: "https://via.placeholder.com/150",
            },
        ],
    },
];


export default menuItems;